export default [
  {
    id: 'q1',
    level: 'beginner',
    text: 'Which of the following best describes React?',
    options: [
      { text: 'A programming language', isCorrect: false },
      { text: 'A library to build user interfaces', isCorrect: true },
      { text: 'A backend framework', isCorrect: false },
      { text: 'A database management system', isCorrect: false },
    ],
  },
  {
    id: 'q2',
    level: 'beginner',
    text: 'What is JSX?',
    options: [
      { text: 'A backend templating engine', isCorrect: false },
      { text: 'A JavaScript extension with HTML-like syntax', isCorrect: true },
      { text: 'A CSS preprocessor', isCorrect: false },
      { text: 'A database query language', isCorrect: false },
    ],
  },
  {
    id: 'q3',
    level: 'beginner',
    text: 'How do you create a functional component?',
    options: [
      { text: 'React.createComponent()', isCorrect: false },
      { text: 'function MyComponent() { return <div /> }', isCorrect: true },
      { text: 'new MyComponent()', isCorrect: false },
      { text: 'class MyComponent {}', isCorrect: false },
    ],
  },
  {
    id: 'q4',
    level: 'beginner',
    text: 'What are props in React?',
    options: [
      { text: 'Lifecycle methods', isCorrect: false },
      { text: 'Inputs passed to components', isCorrect: true },
      { text: 'CSS styles', isCorrect: false },
      { text: 'Internal component state', isCorrect: false },
    ],
  },
  {
    id: 'q5',
    level: 'beginner',
    text: 'What is state in React?',
    options: [
      { text: 'External API data only', isCorrect: false },
      { text: 'Data that controls component behavior', isCorrect: true },
      { text: 'CSS variables', isCorrect: false },
      { text: 'Static HTML content', isCorrect: false },
    ],
  },
  {
    id: 'q6',
    level: 'beginner',
    text: 'Which hook is used for state management?',
    options: [
      { text: 'useMemo', isCorrect: false },
      { text: 'useState', isCorrect: true },
      { text: 'useEffect', isCorrect: false },
      { text: 'useRef', isCorrect: false },
    ],
  },
  {
    id: 'q7',
    level: 'beginner',
    text: 'How do you render lists in React?',
    options: [
      { text: 'Using forEach()', isCorrect: false },
      { text: 'Using map()', isCorrect: true },
      { text: 'Using while loop', isCorrect: false },
      { text: 'Using filter()', isCorrect: false },
    ],
  },
  {
    id: 'q8',
    level: 'beginner',
    text: 'What is the purpose of keys in lists?',
    options: [
      { text: 'Store state', isCorrect: false },
      { text: 'Identify elements uniquely', isCorrect: true },
      { text: 'Style components', isCorrect: false },
      { text: 'Handle events', isCorrect: false },
    ],
  },
  {
    id: 'q9',
    level: 'beginner',
    text: 'What does ReactDOM.render do?',
    options: [
      { text: 'Creates components', isCorrect: false },
      { text: 'Renders React into DOM', isCorrect: true },
      { text: 'Handles routing', isCorrect: false },
      { text: 'Manages state', isCorrect: false },
    ],
  },
  {
    id: 'q10',
    level: 'beginner',
    text: 'What is a fragment used for?',
    options: [
      { text: 'Add styles', isCorrect: false },
      { text: 'Group elements without extra DOM node', isCorrect: true },
      { text: 'Handle state', isCorrect: false },
      { text: 'Manage props', isCorrect: false },
    ],
  },
  {
    id: 'q11',
    level: 'beginner',
    text: 'How do you pass data to child components?',
    options: [
      { text: 'State', isCorrect: false },
      { text: 'Props', isCorrect: true },
      { text: 'Hooks', isCorrect: false },
      { text: 'Refs', isCorrect: false },
    ],
  },
  {
    id: 'q12',
    level: 'beginner',
    text: 'Which is NOT valid conditional rendering?',
    options: [
      { text: 'ternary operator', isCorrect: false },
      { text: '#if syntax', isCorrect: true },
      { text: '&& operator', isCorrect: false },
      { text: 'if statement', isCorrect: false },
    ],
  },
  {
    id: 'q13',
    level: 'beginner',
    text: 'What is lifting state up?',
    options: [
      { text: 'Using global state', isCorrect: false },
      { text: 'Moving state to common parent', isCorrect: true },
      { text: 'Passing props down', isCorrect: false },
      { text: 'Using useEffect', isCorrect: false },
    ],
  },
  {
    id: 'q14',
    level: 'beginner',
    text: 'Which lifecycle method runs after mount?',
    options: [
      { text: 'render', isCorrect: false },
      { text: 'componentDidMount', isCorrect: true },
      { text: 'componentWillUnmount', isCorrect: false },
      { text: 'shouldComponentUpdate', isCorrect: false },
    ],
  },
  {
    id: 'q15',
    level: 'beginner',
    text: 'What are React hooks?',
    options: [
      { text: 'Routing tools', isCorrect: false },
      { text: 'Functions to use state and lifecycle in functional components', isCorrect: true },
      { text: 'CSS utilities', isCorrect: false },
      { text: 'Database connectors', isCorrect: false },
    ],
  },

  // Intermediate
  {
    id: 'q16',
    level: 'intermediate',
    text: 'What does useEffect do?',
    options: [
      { text: 'Manages state', isCorrect: false },
      { text: 'Handles side effects', isCorrect: true },
      { text: 'Creates refs', isCorrect: false },
      { text: 'Optimizes rendering', isCorrect: false },
    ],
  },
  {
    id: 'q17',
    level: 'intermediate',
    text: 'What is React Router?',
    options: [
      { text: 'State manager', isCorrect: false },
      { text: 'Routing library', isCorrect: true },
      { text: 'UI framework', isCorrect: false },
      { text: 'API tool', isCorrect: false },
    ],
  },
  {
    id: 'q18',
    level: 'intermediate',
    text: 'What is Context API used for?',
    options: [
      { text: 'Styling', isCorrect: false },
      { text: 'Global state sharing', isCorrect: true },
      { text: 'DOM manipulation', isCorrect: false },
      { text: 'Routing', isCorrect: false },
    ],
  },
  {
    id: 'q19',
    level: 'intermediate',
    text: 'How to prevent unnecessary re-renders?',
    options: [
      { text: 'useEffect', isCorrect: false },
      { text: 'React.memo', isCorrect: true },
      { text: 'setState', isCorrect: false },
      { text: 'useRef', isCorrect: false },
    ],
  },
  {
    id: 'q20',
    level: 'intermediate',
    text: 'What does useRef provide?',
    options: [
      { text: 'State updates', isCorrect: false },
      { text: 'Persistent mutable value', isCorrect: true },
      { text: 'Re-render trigger', isCorrect: false },
      { text: 'Lifecycle control', isCorrect: false },
    ],
  },
  {
  id: 'q21',
  level: 'intermediate',
  text: 'What is useMemo used for?',
  options: [
    { text: 'Memoizing expensive calculations', isCorrect: true },
    { text: 'Managing state', isCorrect: false },
    { text: 'Handling side effects', isCorrect: false },
    { text: 'Creating refs', isCorrect: false },
  ],
  },
  {
    id: 'q22',
    level: 'intermediate',
    text: 'What is useCallback used for?',
    options: [
      { text: 'Memoizing functions', isCorrect: true },
      { text: 'Handling state', isCorrect: false },
      { text: 'Fetching data', isCorrect: false },
      { text: 'Rendering lists', isCorrect: false },
    ],
  },
  {
    id: 'q23',
    level: 'intermediate',
    text: 'What is controlled component?',
    options: [
      { text: 'Component controlled by state', isCorrect: true },
      { text: 'Component with no state', isCorrect: false },
      { text: 'Component using refs', isCorrect: false },
      { text: 'Component using props only', isCorrect: false },
    ],
  },
  {
    id: 'q24',
    level: 'intermediate',
    text: 'What is uncontrolled component?',
    options: [
      { text: 'Uses refs instead of state', isCorrect: true },
      { text: 'Uses only props', isCorrect: false },
      { text: 'Uses useState only', isCorrect: false },
      { text: 'Uses context API', isCorrect: false },
    ],
  },
  {
    id: 'q25',
    level: 'intermediate',
    text: 'What does key help React with?',
    options: [
      { text: 'Identifying changes in lists', isCorrect: true },
      { text: 'Managing state', isCorrect: false },
      { text: 'Styling components', isCorrect: false },
      { text: 'Handling events', isCorrect: false },
    ],
  },
  {
    id: 'q26',
    level: 'intermediate',
    text: 'What is prop drilling?',
    options: [
      { text: 'Passing props through multiple layers', isCorrect: true },
      { text: 'Using global state', isCorrect: false },
      { text: 'Using hooks', isCorrect: false },
      { text: 'Direct DOM access', isCorrect: false },
    ],
  },
  {
    id: 'q27',
    level: 'intermediate',
    text: 'Which hook replaces componentDidMount?',
    options: [
      { text: 'useEffect', isCorrect: true },
      { text: 'useState', isCorrect: false },
      { text: 'useRef', isCorrect: false },
      { text: 'useMemo', isCorrect: false },
    ],
  },
  {
    id: 'q28',
    level: 'intermediate',
    text: 'What is lazy loading in React?',
    options: [
      { text: 'Loading components on demand', isCorrect: true },
      { text: 'Loading all components at once', isCorrect: false },
      { text: 'Preloading data', isCorrect: false },
      { text: 'Rendering faster UI', isCorrect: false },
    ],
  },
  {
    id: 'q29',
    level: 'intermediate',
    text: 'What does React.StrictMode do?',
    options: [
      { text: 'Highlights potential problems', isCorrect: true },
      { text: 'Improves performance', isCorrect: false },
      { text: 'Adds routing', isCorrect: false },
      { text: 'Handles state', isCorrect: false },
    ],
  },
  {
    id: 'q30',
    level: 'intermediate',
    text: 'What is default export?',
    options: [
      { text: 'Exporting one main value', isCorrect: true },
      { text: 'Exporting multiple values', isCorrect: false },
      { text: 'Importing modules', isCorrect: false },
      { text: 'Handling state', isCorrect: false },
    ],
  },

  // expect
  {
  id: 'q31',
  level: 'expert',
  text: 'What is reconciliation in React?',
  options: [
    { text: 'Updating DOM efficiently', isCorrect: true },
    { text: 'Managing state', isCorrect: false },
    { text: 'Handling API calls', isCorrect: false },
    { text: 'Routing logic', isCorrect: false },
    ],
  },
  {
    id: 'q32',
    level: 'expert',
    text: 'What is virtual DOM?',
    options: [
      { text: 'Lightweight copy of real DOM', isCorrect: true },
      { text: 'Browser DOM', isCorrect: false },
      { text: 'Database structure', isCorrect: false },
      { text: 'API response', isCorrect: false },
    ],
  },
  {
    id: 'q33',
    level: 'expert',
    text: 'What triggers re-render?',
    options: [
      { text: 'State or props change', isCorrect: true },
      { text: 'Console log', isCorrect: false },
      { text: 'CSS change', isCorrect: false },
      { text: 'HTML update', isCorrect: false },
    ],
  },
  {
    id: 'q34',
    level: 'expert',
    text: 'What is batching in React?',
    options: [
      { text: 'Grouping state updates', isCorrect: true },
      { text: 'Splitting components', isCorrect: false },
      { text: 'Lazy loading', isCorrect: false },
      { text: 'Memoizing values', isCorrect: false },
    ],
  },
  {
    id: 'q35',
    level: 'expert',
    text: 'What is hydration?',
    options: [
      { text: 'Attaching events to SSR HTML', isCorrect: true },
      { text: 'Fetching data', isCorrect: false },
      { text: 'Rendering UI', isCorrect: false },
      { text: 'Updating state', isCorrect: false },
    ],
  },
  {
    id: 'q36',
    level: 'expert',
    text: 'What is code splitting?',
    options: [
      { text: 'Splitting bundle into chunks', isCorrect: true },
      { text: 'Splitting components', isCorrect: false },
      { text: 'Splitting state', isCorrect: false },
      { text: 'Splitting props', isCorrect: false },
    ],
  },
  {
    id: 'q37',
    level: 'expert',
    text: 'What is higher-order component (HOC)?',
    options: [
      { text: 'Function returning a component', isCorrect: true },
      { text: 'Component with state', isCorrect: false },
      { text: 'Component using hooks', isCorrect: false },
      { text: 'Component with props', isCorrect: false },
    ],
  },
  {
    id: 'q38',
    level: 'expert',
    text: 'What is render prop pattern?',
    options: [
      { text: 'Passing function as prop', isCorrect: true },
      { text: 'Passing state as prop', isCorrect: false },
      { text: 'Passing JSX', isCorrect: false },
      { text: 'Passing event', isCorrect: false },
    ],
  },
  {
    id: 'q39',
    level: 'expert',
    text: 'What is useReducer used for?',
    options: [
      { text: 'Complex state logic', isCorrect: true },
      { text: 'Simple state', isCorrect: false },
      { text: 'Side effects', isCorrect: false },
      { text: 'Refs', isCorrect: false },
    ],
  },
  {
    id: 'q40',
    level: 'expert',
    text: 'What is React Fiber?',
    options: [
      { text: 'Reconciliation engine', isCorrect: true },
      { text: 'State manager', isCorrect: false },
      { text: 'Router', isCorrect: false },
      { text: 'Library', isCorrect: false },
    ],
  },
  {
    id: 'q41',
    level: 'expert',
    text: 'What is memoization?',
    options: [
      { text: 'Caching results of function', isCorrect: true },
      { text: 'Rendering faster UI', isCorrect: false },
      { text: 'Updating DOM', isCorrect: false },
      { text: 'Handling events', isCorrect: false },
    ],
  },
  {
    id: 'q42',
    level: 'expert',
    text: 'What is SSR?',
    options: [
      { text: 'Server-side rendering', isCorrect: true },
      { text: 'Client rendering', isCorrect: false },
      { text: 'Static routing', isCorrect: false },
      { text: 'State rendering', isCorrect: false },
    ],
  },
  {
    id: 'q43',
    level: 'expert',
    text: 'What is CSR?',
    options: [
      { text: 'Client-side rendering', isCorrect: true },
      { text: 'Server rendering', isCorrect: false },
      { text: 'Static rendering', isCorrect: false },
      { text: 'Routing system', isCorrect: false },
    ],
  },
  {
    id: 'q44',
    level: 'expert',
    text: 'What is Suspense used for?',
    options: [
      { text: 'Handling async loading', isCorrect: true },
      { text: 'Managing state', isCorrect: false },
      { text: 'Routing', isCorrect: false },
      { text: 'Styling', isCorrect: false },
    ],
  },
  {
    id: 'q45',
    level: 'expert',
    text: 'What is concurrent rendering?',
    options: [
      { text: 'Interruptible rendering', isCorrect: true },
      { text: 'Parallel API calls', isCorrect: false },
      { text: 'Multiple DOM updates', isCorrect: false },
      { text: 'Batch updates', isCorrect: false },
    ],
  },

];